name: Latest blog post workflow

permissions:
  contents: write

on:
  push:                     # runs once immediately when you push this workflow file
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"     # runs once daily at midnight UTC
  workflow_dispatch:        # allows manual trigger from Actions tab

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://medium.com/feed/@shubh1515"
